# Generated by Django 4.2.4 on 2023-08-21 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_data', '0002_announcedpuresult_announcedstateresult_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcedpuresult',
            table='announced_pu_results',
        ),
        migrations.AlterModelTable(
            name='announcedstateresult',
            table='announced_state_results',
        ),
        migrations.AlterModelTable(
            name='announcedwardresult',
            table='announced_ward_results',
        ),
    ]
