
# Use an official Python runtime as a parent image
FROM python:3.8-slim

# set env variables
ENV MYSQLCLIENT_CFLAGS="-I/usr/include/mysql"
ENV MYSQLCLIENT_LDFLAGS="-L/usr/lib/x86_64-linux-gnu -lmysqlclient"

# Set the working directory to /app
WORKDIR /app

# Install dev tools including gcc
RUN apt-get update && \
    apt-get install -y gcc libmariadb-dev-compat  && \
    rm -rf /var/lib/apt/lists/*

# Install the mysqlclient Python package
RUN pip install mysqlclient


# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Make port 8000 available to the world outside this container
EXPOSE 8000


# Run app.py when the container launches
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
